-- MySQL Script generated by MySQL Workbench
-- 04/03/16 21:00:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema moonrise_crystals_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema moonrise_crystals_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `moonrise_crystals_database` DEFAULT CHARACTER SET utf8 ;
USE `moonrise_crystals_database` ;

-- -----------------------------------------------------
-- Table `moonrise_crystals_database`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moonrise_crystals_database`.`customers` (
  `customer_id` SMALLINT(6) NOT NULL AUTO_INCREMENT COMMENT '',
  `first_name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `last_name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `username` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `email` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `phone_number` VARCHAR(20) NULL DEFAULT NULL COMMENT '',
  `address` VARCHAR(100) NULL DEFAULT NULL COMMENT '',
  `city` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `state` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `zip` VARCHAR(20) NULL DEFAULT NULL COMMENT '',
  `country` VARCHAR(45) NULL DEFAULT 'USA' COMMENT '',
  `notes` TEXT NULL DEFAULT NULL COMMENT '',
  `deleted` TINYINT(1) NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`customer_id`)  COMMENT '',
  UNIQUE INDEX `Username_UNIQUE` (`username` ASC)  COMMENT '',
  UNIQUE INDEX `Email_UNIQUE` (`email` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 1456
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `moonrise_crystals_database`.`platforms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moonrise_crystals_database`.`platforms` (
  `platform_id` VARCHAR(10) NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`platform_id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `moonrise_crystals_database`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moonrise_crystals_database`.`orders` (
  `order_id` SMALLINT(6) NOT NULL AUTO_INCREMENT COMMENT '',
  `customer_id` SMALLINT(6) NOT NULL COMMENT '',
  `platform_id` VARCHAR(10) NOT NULL COMMENT '',
  `date` DATE NULL DEFAULT NULL COMMENT '',
  `additional_cost` DECIMAL(10,2) NULL DEFAULT '0.00' COMMENT '',
  `notes` TEXT NULL DEFAULT NULL COMMENT '',
  `repeat_customer` VARCHAR(10) NULL DEFAULT NULL COMMENT '',
  `status` SMALLINT(6) NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`order_id`)  COMMENT '',
  INDEX `idx Customer_ID` (`customer_id` ASC)  COMMENT '',
  INDEX `idx Platform_ID` (`platform_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Orders_Customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `moonrise_crystals_database`.`customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Platforms1`
    FOREIGN KEY (`platform_id`)
    REFERENCES `moonrise_crystals_database`.`platforms` (`platform_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1277
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `moonrise_crystals_database`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moonrise_crystals_database`.`products` (
  `product_id` SMALLINT(6) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `default_price` DECIMAL(10,2) NOT NULL DEFAULT '0.00' COMMENT '',
  `status` SMALLINT(6) NULL DEFAULT '0' COMMENT '',
  `quantity` SMALLINT(6) NULL DEFAULT '0' COMMENT '',
  `first_stone_earning` DECIMAL(10,4) NULL DEFAULT '0.0000' COMMENT '',
  `second_stone_earning` DECIMAL(10,4) NULL DEFAULT '0.0000' COMMENT '',
  `third_stone_earning` DECIMAL(10,4) NULL DEFAULT '0.0000' COMMENT '',
  `inventory_cost` DECIMAL(10,4) NULL DEFAULT '0.0000' COMMENT '',
  PRIMARY KEY (`product_id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 215
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `moonrise_crystals_database`.`order_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moonrise_crystals_database`.`order_details` (
  `order_id` SMALLINT(6) NOT NULL COMMENT '',
  `product_id` SMALLINT(6) NOT NULL COMMENT '',
  `quantity` SMALLINT(6) NULL DEFAULT NULL COMMENT '',
  `price` DECIMAL(10,2) NULL DEFAULT NULL COMMENT '',
  `first_stone_earning` DECIMAL(10,4) NULL DEFAULT '0.0000' COMMENT '',
  `second_stone_earning` DECIMAL(10,4) NULL DEFAULT '0.0000' COMMENT '',
  `third_stone_earning` DECIMAL(10,4) NULL DEFAULT '0.0000' COMMENT '',
  `order_details_id` SMALLINT(6) NOT NULL AUTO_INCREMENT COMMENT '',
  `feedback_message` TEXT NULL DEFAULT NULL COMMENT '',
  `inventory_cost` DECIMAL(10,4) NULL DEFAULT '0.0000' COMMENT '',
  PRIMARY KEY (`order_details_id`)  COMMENT '',
  INDEX `idx FK Product_ID` (`product_id` ASC)  COMMENT '',
  INDEX `idx FK Order_ID` (`order_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Orders_has_Products_Orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `moonrise_crystals_database`.`orders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_has_Products_Products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `moonrise_crystals_database`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2871
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `moonrise_crystals_database`.`vendors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moonrise_crystals_database`.`vendors` (
  `vendor_id` SMALLINT(6) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(100) NOT NULL COMMENT '',
  `contact_person` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `phone_number` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `address` VARCHAR(100) NULL DEFAULT NULL COMMENT '',
  `website` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `email` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `country` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `deleted` TINYINT(1) NULL DEFAULT '0' COMMENT '',
  `notes` TEXT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`vendor_id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `moonrise_crystals_database`.`product_vendor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moonrise_crystals_database`.`product_vendor` (
  `unique_id` SMALLINT(6) NOT NULL AUTO_INCREMENT COMMENT '',
  `date_added` DATE NOT NULL COMMENT '',
  `product_id` SMALLINT(6) NOT NULL COMMENT '',
  `vendor_id` SMALLINT(6) NOT NULL COMMENT '',
  `weight` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `cost` DECIMAL(10,2) NULL DEFAULT NULL COMMENT '',
  `quantity` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `quality` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `notes` TEXT NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`unique_id`, `date_added`, `product_id`, `vendor_id`)  COMMENT '',
  INDEX `fk_product_vendor_products1_idx` (`product_id` ASC)  COMMENT '',
  INDEX `fk_product_vendor_vendors1_idx` (`vendor_id` ASC)  COMMENT '',
  CONSTRAINT `fk_product_vendor_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `moonrise_crystals_database`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_vendor_vendors1`
    FOREIGN KEY (`vendor_id`)
    REFERENCES `moonrise_crystals_database`.`vendors` (`vendor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 73
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
